"""added numOfAnimals column to posts

Revision ID: 3cbbe5c4d104
Revises: b69c7bb6e1c3
Create Date: 2024-01-30 15:44:13.908273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbbe5c4d104'
down_revision = 'b69c7bb6e1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numOfAnimals', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('numOfAnimals')

    # ### end Alembic commands ###
