"""added numOfAnimals column to posts

Revision ID: 4790d3f740ec
Revises: 3cbbe5c4d104
Create Date: 2024-01-30 15:45:10.914291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4790d3f740ec'
down_revision = '3cbbe5c4d104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numOfAnimals', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('numOfAnimals')

    # ### end Alembic commands ###
