"""fixed typo on user animal many to many table

Revision ID: 56097dd07e6b
Revises: 9a3c6d30a54e
Create Date: 2024-01-18 13:27:04.784710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56097dd07e6b'
down_revision = '9a3c6d30a54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_animal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_animal_user_id_animals', type_='foreignkey')
        batch_op.drop_constraint('fk_user_animal_animal_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_animal_animal_id_animals'), 'animals', ['animal_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_animal_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_animal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_animal_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_animal_animal_id_animals'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_animal_animal_id_users', 'users', ['animal_id'], ['id'])
        batch_op.create_foreign_key('fk_user_animal_user_id_animals', 'animals', ['user_id'], ['id'])

    # ### end Alembic commands ###
