"""added relationship for tagged animals and users

Revision ID: 9a3c6d30a54e
Revises: ec20899dfca0
Create Date: 2023-12-12 12:48:43.476072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3c6d30a54e'
down_revision = 'ec20899dfca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_animal',
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['users.id'], name=op.f('fk_user_animal_animal_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['animals.id'], name=op.f('fk_user_animal_user_id_animals'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_animal')
    # ### end Alembic commands ###
