"""added more image column slots for posts

Revision ID: b69c7bb6e1c3
Revises: 1c28406b96a7
Create Date: 2024-01-30 15:41:55.846763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69c7bb6e1c3'
down_revision = '1c28406b96a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgOne', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imgTwo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imgThree', sa.String(), nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('imgThree')
        batch_op.drop_column('imgTwo')
        batch_op.drop_column('imgOne')

    # ### end Alembic commands ###
