"""added animal and post relationship

Revision ID: ec20899dfca0
Revises: 6b65032027a9
Create Date: 2023-12-12 12:30:48.547158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec20899dfca0'
down_revision = '6b65032027a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_post',
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_animal_post_animal_id_animals')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_animal_post_post_id_posts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_post')
    # ### end Alembic commands ###
